name: Output issues event details
on: issues
jobs:
  info:
    runs-on: ubuntu-20.04
    steps:
      - name: Output Github context
        run: echo $JSON
        env:
          JSON: ${{ toJSON(github) }}